export const nodeConstants = {
    ADD_NODE : "ADD_NODE", 
    DELETE_NODE : "DELETE_NODE", 
    LIST_NODES : "LIST_NODES",   
    UPDATE_NODES : "UPDATE_NODES",
    TYPE_OF_NODES : "TYPE_OF_NODES",
    UPDATE_NODES_CONN : "UPDATE_NODES_CONN"  
} 